-- Do not manually edit this file, it was auto-generated by yonigibbs/elm-i18next-gen
-- https://github.com/yonigibbs/elm-i18next-gen


module Translations exposing (..)

import I18Next exposing (Delims(..), Translations, t, tr)


music : Translations -> String
music translations =
    t translations "music"


movies : Translations -> String
movies translations =
    t translations "movies"


tvShows : Translations -> String
tvShows translations =
    t translations "tv shows"


browser : Translations -> String
browser translations =
    t translations "browser"


addOns : Translations -> String
addOns translations =
    t translations "add-ons"


thumbsUp : Translations -> String
thumbsUp translations =
    t translations "thumbs up"


playlists : Translations -> String
playlists translations =
    t translations "playlists"


settings : Translations -> String
settings translations =
    t translations "settings"


help : Translations -> String
help translations =
    t translations "help"
