name: "continuous-integration"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jorelali/setup-elm@v5
        with:
          elm-version: 0.19.1
      - run: node -v
      - run: npm install
      - run: npm run-script build

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          elm-version: 0.19.1
      - run: npx elm-format src/ --validate
